---
title: Consumer Price vs Production Cost Explorer
runtime: shiny
output:
    flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(knitr)
library(flexdashboard)
library(sf)
library(magrittr)
```

```{r data, include=FALSE}
data <- readRDS("data.rds")
regions <- readRDS("regions.rds")
```

# Price vs Cost Map

## Cart Inputs {.sidebar data-width="400"}

```{r cart}

# Product Selection

shiny::hr()

shiny::p('Set prices for products in the "Pricing Generator" tab. By default, retail prices are set to $1 above the production cost, and shipping prices are set to the maximum shipping cost across all product types in a region.')

shiny::selectizeInput(
  "products",
  "Products in Cart",
  choices = sort(unique(data$product)),
  multiple = TRUE,
  width = "99%"
)

shiny::actionButton(
  "calculate",
  "Calculate Prices and Costs by Region",
  width = "99%"
)

display_choices <- c(
  "Markup ($)" = "price_markup_dollars",
  "Markup (%)" = "price_markup_percent",
  "Total Price" = "total_price",
  "Total Cost" = "total_cost"
)

shiny::selectInput(
  "map_display", "Map Display Layer",
  choices = display_choices,
  selected = "price_markup_percent",
  width = "99%"
)

shiny::p("Add or delete items from the cart using the input above. Double click on a Quantity cell below to edit.")
shiny::p("Note that non-integer quantities will be rounded, and values below 1 will be treated as excluding the item from the cart.")

cart_table <- shiny::reactiveValues(tbl = tibble::tibble(Product = character(), Quantity = integer()))

DT::DTOutput("cart", width = "99%")

output$cart <- DT::renderDT({
  cart_table$tbl %>% 
    DT::datatable(
      editable = list(target = "cell", disable = list(columns = 0)),
      rownames = FALSE,
      options = list(searching = FALSE)
    )
})

cart_proxy <- DT::dataTableProxy("cart")

shiny::observeEvent(input$products, {
  add_to_cart <- setdiff(input$products, cart_table$tbl$Product)
  remove_from_cart <- setdiff(cart_table$tbl$Product, input$products)
  
  new_tbl <- dplyr::bind_rows(
    dplyr::filter(cart_table$tbl, !Product %in% remove_from_cart),
    tibble::tibble(Product = add_to_cart, Quantity = rep(1, length(add_to_cart)))
  )

  cart_table$tbl <- new_tbl
})

shiny::observeEvent(input$cart_cell_edit, {
  info = input$cart_cell_edit
  info$col <- info$col + 1
  
  cart_table$tbl <- DT::editData(
    data = cart_table$tbl,
    info, cart_proxy, resetPaging = FALSE
  )
})
```

## Map

```{r initial_map}
output$map <- leaflet::renderLeaflet({
  leaflet::leaflet("map") %>% 
    leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) %>% 
    leaflet::setView(0, 0, zoom = 2)
})
leaflet::leafletOutput("map", width = "100%", height = "100%")

pal <- leaflet::colorNumeric(
  palette = "YlOrRd",
  domain = NULL
)
```

# Pricing Generator


```{r calculate}

shiny::observeEvent(c(input$calculate, input$map_display), {
  compare <- cost_price_table$tbl %>%
    dplyr::inner_join(cart_table$tbl, by = c("product" = "Product")) %>%
    dplyr::transmute(
      retail_price,
      shipping_price,
      production_cost = max_production_cost,
      shipping_cost = shipping_cost + ((Quantity - 1) * additional_shipping)
    ) %>%
    dplyr::group_by(region) %>%
    dplyr::summarize_all(sum) %>%
    dplyr::mutate(
      total_price = retail_price + shipping_price,
      total_cost = production_cost + shipping_cost,
      price_markup_dollars = total_price - total_cost,
      price_markup_percent = price_markup_dollars / total_cost
    ) %>%
    {dplyr::left_join(regions, ., by = "region")}

  leaflet::leafletProxy("map", data = compare) %>%
    leaflet::clearGroup("Result") %>%
    leaflet::clearControls() %>% 
    leaflet::addPolygons(
      color = "#ffffffff",
      weight = 1,
      fillOpacity = 0.2,
      fillColor = pal(compare[[input$map_display]]),
      popup = ~glue::glue(
        "<b>{name_long}</b><br/>
        <b>Shipping Region:</b> {region}</br>
        <b>Total Price:</b> {scales::dollar(total_price, accuracy = 0.01)}</br>
        <b>Total Cost:</b> {scales::dollar(total_cost, accuracy = 0.01)}</br>
        <b>Markup ($):</b> {scales::dollar(price_markup_dollars, accuracy = 0.01)}</br>
        <b>Markup (%):</b> {scales::percent(price_markup_percent, accuracy = 1)}"
      ),
      group = "Result"
    ) %>% 
    leaflet::addLegend(
      pal = pal,
      values = compare[[input$map_display]],
      title = names(display_choices[display_choices == input$map_display])
    )
}, ignoreInit = TRUE, ignoreNULL = TRUE)

```

### Premade Strategies {data-height="200"}

```{r pricing_strategies}
shiny::p("As we develop heuristics and algorithms to set prices across the inventory, buttons to implement them will be added in this section.")
```

### Table

```{r pricing_table}
shiny::p('The "retail_price" and "shipping_price" columns are editable.')
shiny::p("As per the Squarespace constraints motivating this problem, setting a retail_price for a product will set it across all regions, and setting a shipping price for a region will set it across all products.")

cost_price_table <- shiny::reactiveValues(
  tbl = data
)

DT::DTOutput("cost_price_table", width = "99%", height = "100%")

output$cost_price_table <- DT::renderDT({
  table <- cost_price_table$tbl %>% 
    DT::datatable(
      rownames = FALSE,
      fillContainer = TRUE,
      editable = list(target = "cell", disable = list(columns = c(0, 3:ncol(.))))
    )
})

table_proxy <- DT::dataTableProxy("cost_price_table")

shiny::observeEvent(input$cost_price_table_cell_edit, {
  info = input$cost_price_table_cell_edit
  info$col <- info$col + 1

  cost_price_table$tbl <- DT::editData(
    data = cost_price_table$tbl,
    info, table_proxy, resetPaging = FALSE
  )
  
  tbl <- cost_price_table$tbl

  if (info$col == 2) {
    # set price for all regions
    prod <- tbl[info$row, ]$product
    tbl <- dplyr::mutate(tbl, retail_price = dplyr::if_else(product == prod, as.numeric(info$value), retail_price))
  } else if (info$col == 3) {
    # set shipping price for all products in region
    reg <- tbl[info$row, ]$region
    tbl <- dplyr::mutate(tbl, shipping_price = dplyr::if_else(region == reg, as.numeric(info$value), shipping_price))
  }
  
  cost_price_table$tbl <- tbl
})
```